plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - buku-pegangan-pemain/Pendahuluan.md
  - buku-pegangan-pemain/pendahuluan/DuniaPetualangan.md
